stages:
- name: envsubst
  steps:
  - runScriptConfig:
      image: alpine:latest
      shellScript: 'export WEBAPPVERSION=v1.0.9 && /usr/bin/envsubst < kubernetes/webapp-deployment.yaml '
timeout: 60
notification: {}
