stages:
- name: Build Docker
  steps:
  - publishImageConfig:
      dockerfilePath: web/Dockerfile
      buildContext: .
      tag: godofneon/web-app
      pushRemote: true
      registry: index.docker.io
- name: Kubernetes
  steps:
  - applyYamlConfig:
      path: kubernetes/webapp-deployment.yaml
    env:
      repository: godofneon/web-app
      version: v1.0.8
timeout: 60
notification: {}
