stages:
- name: envsubst
  steps:
  - runScriptConfig:
      image: alpine:latest
      shellScript: export WEBAPPVERSION=v1.0.9 && sed -i "s/{{WEBAPPVERSION}}/$WEBAPPVERSION/g"
        kubernetes/webapp-deployment.yaml
- name: K8s
  steps:
  - applyYamlConfig:
      path: ./kubernetes/webapp-deployment.yaml
timeout: 60
notification: {}
